### ISSUE TITLE
Pregunta 1.2

### ISSUE THREAD

**Issue by Alonsinho1** [IIC2513-2020-2/interrogation-one#1]
Hola en la pregunta 1.2 a que se refiere exactamente que no lo podemos escribir a mano?  La razon es por que no podemos asumir que estos tres atributos siempre vienen en el mismo orden? Que hay una cantidad arbitraria de atributos y debemos filtrar los que contengan estos valores?

**Comment by meretamal** [comment]
Hola Alonso, las issues se están respondiendo en el repositorio del curso. Entre ellas hay una con un pin que tiene las cosas que se discutieron hoy en clases, en donde se habló de esto mismo
